In [14]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

In [23]:
C = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(f"""{C}
Сума всіх елементів: {C.sum()}
Добуток всіх елементів: {C.prod()}

Мінімальний елемент: {C.min()}
Максимальний елемент: {C.max()}

Середнє значення: {C.mean()}
Девіація (відхилення): {C.std()}

Заокруглили всі значення:
{np.round(C)}
Tа знайшли унікальні величини: {np.unique(np.round(C))}
Та порахувавли кількість унікальних значеннь: {np.unique(np.round(C), return_counts=True)[1]}

""")

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]
Сума всіх елементів: 4.8595784
Добуток всіх елементів: 1.4517216120884712e-06

Мінімальний елемент: 0.05093587
Максимальний елемент: 0.82485143

Середнє значення: 0.4049648666666667
Девіація (відхилення): 0.21392120766089617

Заокруглили всі значення:
[[0. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 0. 1.]]
Tа знайшли унікальні величини: [0. 1.]
Та порахувавли кількість унікальних значеннь: [7 5]




In [16]:
print(f"""{C}
Сума елементів по стовпцях: {C.sum(axis=0)}
Сума елементів по рядках: {C.sum(axis=1)}

Добуток елементів по стовпцях: {C.prod(axis=0)}
Добуток елементів по рядках: {C.prod(axis=1)}

Мінімальний елемент по стовпцях: {C.min(axis=0)}
Мінімальний елемент по рядках: {C.min(axis=1)}
Максимальний елемент по стовпцях: {C.max(axis=0)}
Максимальний елемент по рядках: {C.max(axis=1)}

Середнє значення по стовпцях: {C.mean(axis=0)}
Девіація (відхилення) по стовпцях: {C.std(axis=0)}

""")

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]
Сума елементів по стовпцях: [1.12378257 1.04875507 1.01034462 1.67669614]
Сума елементів по рядках: [1.51832856 1.55434556 1.78690428]

Добуток елементів по стовпцях: [0.03125066 0.00726716 0.03662519 0.17453384]
Добуток елементів по рядках: [0.01476228 0.00620385 0.01585143]

Мінімальний елемент по стовпцях: [0.12697628 0.05093587 0.26590556 0.5510652 ]
Мінімальний елемент по рядках: [0.17296777 0.05093587 0.12697628]
Максимальний елемент по стовпцях: [0.54627315 0.82485143 0.40067661 0.56917101]
Максимальний елемент по рядках: [0.5510652  0.55645993 0.82485143]

Середнє значення по стовпцях: [0.37459419 0.34958502 0.33678154 0.55889871]
Девіація (відхилення) по стовпцях: [0.1794018  0.33973673 0.05524104 0.00759016]


